name: real_time_quiz_professor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.4
  uuid: ^4.2.1
  intl: ^0.20.2
  image_picker: ^1.0.7
  image_picker_web: ^4.0.0   
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    # - assets/icons/
    # - assets/fonts/